### PR TITLE
Document generic systemIds

### PR DESCRIPTION
**Pull request by mvahowe**
Removes the org whitelist from the schema and removes non-id content from systemIds. (The schema changes got pushed to master - oops!)

### CODE REVIEW

**Comment by mvahowe** [comment]
I've made quite extensive changes on the basis of yesterday's conversation. (Unfortunately, the diff isn't much help since I also reformatted the schema to the default Oxygen layout. This should at least make future diffs more useful.)

I removed \@id from the root element. At this point, \@revision had to go too, and needed somewhere to live. So systemId now optionally takes \@revision. At least one systemId must have a \@revision (although this is not currently enforced).

systemId is unchanged. Re the localhost conversation yesterday, this is why we have a \@local attribute, which has been presented and documented since forever. Without something like this, even unit testing of a toolchain requires DNS spoofing, and it also allows intranet-type functionality. The documentation makes clear that this is a caveat emptor kind of thing.

The id format is currently a prefix and an arbitrary non-space string, separated by 2 colons, eg

```
dbl::0123456789abcdef
dbl::burrito/user/99
```
I think :: is better than : as a separator as :: is less likely to be used in the system-specific string, but also because it's a bad idea for XML schema to include things that look like XML namespaces but aren't. (@jag3773 I also removed your use of "namespace" in the id documentation because that would baffle any XML-aware reader.)

The use of URL paths for the system-specific part of the ID would help with discoverability and is what I expect DBL to do (it was @smorrison's idea) , but is not required by the schema.

I removed \@prefix from systemId and, instead, added the prefix to the enclosed id. This means that ids look the same everywhere in the document.

Along the way I tweaked various other things, including removing the requirement for the type element to be near the top of the document. (This seemed like a good idea when the type element was concise, but it now contains the flavor-specific information which can be huge, and it's a pain to have to scroll or SAX through this to find the id or the name of the burrito.)

In the example text document it looks something like this:
```
<burritoMetadata schemaVersion="0.1">
    <idServer prefix="dbl">https://thedigitalbiblelibrary.org</idServer>
    <idServer prefix="agmt" >http://registry.autographamt.com</idServer>
    <idServer prefix="x-atl">http://atlantisbibleconsortium.net</idServer>
    <idServer prefix="myServer" local="true">http://localhost:8080</idServer>
    <identification>
        <systemId revision="23">dbl::0123456789abcdef</systemId>
        <systemId>gbc::55df02965117ad3f2201309b</systemId>
        <systemId>paratext::2d5220a02a7aaac6bcc2831ae262e9aaca5e1abd</systemId>
...
    </identification>
    <relationships>
        <relation flavor="scripturePrint" relationType="expression" id="dbl::fedcba9876543210" revision="2"/>
        <relation flavor="glossedTextStory" relationType="expression" id="x-atl::gl47" revision="1.2.3"/>
        <relation relationType="parascriptural" flavor="parascripturalWordAlignment" id="agmt::irvmal-4-wh" revision="1"/>
    </relationships>
    <agencies>
        <contributor>
            <id>dbl::23</id>
...
        </contributor>
        <administrator>
            <id>dbl::29</id>
            <name lang="en">We Manage Burritos</name>
        </administrator>
    </agencies>
...
    <snapshot>
        <creation>
            <software>Burrito Factory 0.1</software>
            <user id="dbl::1234">Jane Doe</user>
        </creation>
        <uploading>
            <software>Burrito Truck 0.1</software>
            <user id="dbl::5678"/>
        </uploading>
        <comments>Experimenting with i18n</comments>
    </snapshot>
</burritoMetadata>
```
I have attempted to update the documentation, although I suspect we'll catch some remaining inconsistencies on the final proof reading before 0.1 beta.

**Comment by rdb** [comment]
Is there actually any reason for the `x-` prefix now?

**Comment by mvahowe** [comment]
@rdb There's no schema reason, I left it there because it's allowed, and because, for me, it functions a bit like a leading underscore, ie it's not something intended as an external interface. I can remove it if others find it confusing.

**Comment by rdb** [comment]
I only wondered because it might give the impression that there is semantic value in the `x-` prefix in particular, as opposed to an arbitrarily chosen prefix.

Anyway, all this LGTM from a cursory glance.

**Comment by mvahowe** [comment]
@rdb Ok, x- ids have left the building.

**Comment by jonathanrobie** [comment]
This is looking much better.

I would be inclined to put both <idServer/> and <systemIdentifier/> elements inside the <identification/> element.

**Comment by mvahowe** [comment]
> What is our general policy toward collections?
 
> There is a set of `<idServer/>` elements without a containing element, and a bunch of `<systemIdentifier/>` elements inside the `<identification/>` element.

I think I'd be the only person here right now who might have a policy, and it's more a set of hunches. My logic here was something like

* idServer goes at the top level because their scope is global, and because they are one thing that ought to be forced to the top of the document

* systemId (in general) is an indentification sort of thing (identification contains a lot of other fields that I elided in the PR fragment).

* in general, I favour no-wrapper collections because it's trivial to collect similar things in XPath, but I make an exception when this starts to make for huge, flat laundry lists.

Things have changed since I made these decisions, since, previously, the systemId of the entire document was in the root element, and the systemIds in identification were "secondary". As of today we have the id of the document itself under identification, which does feel a little too nested. On the other hand, I rejected the option to have one systemId under root and the others under identification because that seemed inconsistent. Also, although I don't pretend to have thought all the scenarios through to the end, I think we could imagine a system that pushes simultaneously to two servers, in which case there would be two "primary" systemIds, one for each system.

@jonathanrobie Can we live with this for now? If not, what does your preferred solution look like?

**Comment by jonathanrobie** [comment]
I can certainly live with this for 0.1 beta.

After that, we might want to make a list of guidelines for how we structure things in XML to make sure we are being consistent and creating things that are easy to search and query efficiently.

**Pull request merged**
