### PR TITLE
Contributors

### PR DESCRIPTION
**Pull request by jtauber**
- [x] update license
- [x] decide on criteria for inclusion
- [x] populate initial CONTRIBUTORS list

### CODE REVIEW

**Comment by jtauber** [comment]
Need to get affiliations. Should they include historical affiliations?

James Tauber <jtauber@jtauber.com>
Jonathan Robie <jonathan.robie@gmail.com>
Jesse Griffin <jesse.griffin@unfoldingword.org>
Joel Mathew <mail@joelmath.io>
Tim Steenwyk <tim_steenwyk@sil.org>
Eric Pyle <eric_pyle@sil.org>

**Comment by jtauber** [comment]
Commits to repo:

   251  Mark Howe <mvahowe@gmail.com>
    97  James Tauber <jtauber@jtauber.com>
    79  Jesse Griffin <jesse.griffin@unfoldingword.org>
    51  Jesse Griffin <jag3773@gmail.com>
    13  rdb <git@rdb.name>
    11  sean <morriss@me.com>
    10  Sean Morrison <morriss@me.com>
     6  Jonathan Robie <jonathan.robie@gmail.com>
     5  Joel Mathew <joelmathew.mec@gmail.com>
     4  rdb <rdb@users.noreply.github.com>
     3  katherinejensen00 <katherinejensen00@gmail.com>
     1  Fool Running <TimeToStay@hotmail.com>
     1  James Cuénod <jcuenod@users.noreply.github.com>
     1  benVar <beniza@users.noreply.github.com>

**Comment by FoolRunning** [comment]
Note that Fool Running is me (Tim Steenwyk).

**Comment by jag3773** [comment]
LGTM

**Comment by joelthe1** [comment]
LGTM 👍

**Pull request merged**
