### PR TITLE
Example reference format file

### PR DESCRIPTION
**Pull request by mvahowe**
This PR provides a schema and example document for USFM reference parsing settings as JSON.

The schema is underspecified in terms of what should be required and how those fields may be constrained (eg I suspect most of them should be non-alphanumeric characters).

Tests should pass because they don't actually test the schema or test document, yet.

### CODE REVIEW

**Comment by mvahowe** [comment]
Relates to #139

**Comment by mvahowe** [comment]
To progress this I think we need @FoolRunning to tell us where we might expect multiple values, rather than the single value assumed in the current schema.

**Comment by FoolRunning** [comment]
Sorry, I forgot about this.
In Paratext, the following settings can contain multiple entries/values:
* **rangeIndicator**
* **sequenceIndicator**
* **chapterRangeSeparator**
* **chapterNumberSeparator**
* **bookSequenceSeparator**
* **referenceExtraMaterial** (already allows multiple values)

Also, the **bookSourceForMarkerXt** and **bookSourceForMarkerR** settings have values that are an enumeration: **LongName**, **ShortName**, **Abbreviation** and can not be blank/null.

Also (again), the **referenceExtraMaterial** and **referenceFinalPunctuation** values are optional and can be blank/null - in which case validation fails if those things were to be specified in a reference. Since we're not doing validation, it might be possible to just ignore these two settings.

**Comment by mvahowe** [comment]
@FoolRunning Thanks! When you say "not doing validation", you mean against the versification for that entry? If so, I agree that we're not doing it. (We do need to validate the syntax of the references.)

**Comment by FoolRunning** [comment]
@mvahowe, I thought this was just to get the **loc** attributes set. If so, then we just have to be able to parse the reference, right?

**Pull request merged**
