### PR TITLE
Versification JSON schema plus example document

### PR DESCRIPTION
**Pull request by mvahowe**
This PR relates to #49. The details were discussed in the Copenhagen Alliance versification meetings. Things to note include

* We should probably constrain the partial verse strings but I'm not sure how. (I did see an issue with validation of partial verse segments in USX3 recently which suggests that it's not trivial.)

* The verification section is fairly free form because, right now, we have no clue about the details of present or future verifiers. I thought that the bare minimum information we need is the name of the verifier and what the boolean result was.

@jonathanrobie I assume we want to hold this PR for the next Versification committee meeting? Maybe we could invite them to take a look here before the next meeting?

### CODE REVIEW

**Comment by mvahowe** [comment]
The versification WG signed off on this yesterday, so I think we can merge this. The next steps are 

- finalising the versification flavor which will have this JSON as probably its only ingredient
- making this the required format for versification in the textTranslation flavor.

**Comment by jonathanrobie** [comment]
The specification itself goes into the Copenhagen Alliance repo, I think.

Jonathan

**Comment by jonathanrobie** [comment]
I created this directory in the Copenhagen Alliance repository:

https://github.com/Copenhagen-Alliance/copenhagen-alliance.github.io/tree/master/specifications/versification

**Comment by jonathanrobie** [comment]
The Copenhagen Alliance directory is now committed here:

https://github.com/Copenhagen-Alliance/copenhagen-alliance.github.io/tree/master/specifications/versification

I have not yet connected this to the main public page, I'll do that after we discuss.

**Comment by jag3773** [comment]
@jonathanrobie Shouldn't the versification schema be in it's own repository in https://github.com/Copenhagen-Alliance/ ?

**Pull request closed without merging**
