### PR TITLE
Release 1.0.0-rc1

### PR DESCRIPTION
**Pull request by jtauber**
- copyright schema improvements
- ingredients now required
- names renamed to localizedNames and made optional
- idAuthority now required
- defaultLanguage changed to defaultLocale

### CODE REVIEW

**Comment by jag3773** [comment]
LGTM!

**Comment by joelthe1** [comment]
Yes, LGTM 👍

**Comment by FoolRunning** [comment]
Approved! 👍

**Comment by jag3773** [comment]
@jtauber Now that I have the link on the main page fixed, I think we are ready to release, right?

**Pull request merged**
